// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: db.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SquickStruct {

  /// <summary>Holder for reflection information generated from db.proto</summary>
  public static partial class DbReflection {

    #region Descriptor
    /// <summary>File descriptor for db.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DbReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CghkYi5wcm90bxIMU3F1aWNrU3RydWN0GgpiYXNlLnByb3RvIpUBCgpQbGF5",
            "ZXJEYXRhEiMKBm9iamVjdBgBIAEoCzITLlNxdWlja1N0cnVjdC5JZGVudBIy",
            "Cghwcm9wZXJ0eRgCIAEoCzIgLlNxdWlja1N0cnVjdC5PYmplY3RQcm9wZXJ0",
            "eUxpc3QSLgoGcmVjb3JkGAMgASgLMh4uU3F1aWNrU3RydWN0Lk9iamVjdFJl",
            "Y29yZExpc3Qq6AEKBURiUlBDEg8KC0RCX1JQQ19OT05FEAASFQoPUkVRX1BM",
            "QVlFUl9MSVNUELDqARIVCg9BQ0tfUExBWUVSX0xJU1QQseoBEhcKEVJFUV9Q",
            "TEFZRVJfQ1JFQVRFELLqARIXChFSRVFfUExBWUVSX0RFTEVURRCz6gESGgoU",
            "UkVRX1BMQVlFUl9EQVRBX0xPQUQQtOoBEhoKFEFDS19QTEFZRVJfREFUQV9M",
            "T0FEELXqARIaChRSRVFfUExBWUVSX0RBVEFfU0FWRRC26gESGgoUQUNLX1BM",
            "QVlFUl9EQVRBX1NBVkUQt+oBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SquickStruct.BaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SquickStruct.DbRPC), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SquickStruct.PlayerData), global::SquickStruct.PlayerData.Parser, new[]{ "Object", "Property", "Record" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 30000 ~ 35000
  /// </summary>
  public enum DbRPC {
    [pbr::OriginalName("DB_RPC_NONE")] None = 0,
    [pbr::OriginalName("REQ_PLAYER_LIST")] ReqPlayerList = 30000,
    [pbr::OriginalName("ACK_PLAYER_LIST")] AckPlayerList = 30001,
    [pbr::OriginalName("REQ_PLAYER_CREATE")] ReqPlayerCreate = 30002,
    [pbr::OriginalName("REQ_PLAYER_DELETE")] ReqPlayerDelete = 30003,
    /// <summary>
    /// 加载玩家数据
    /// </summary>
    [pbr::OriginalName("REQ_PLAYER_DATA_LOAD")] ReqPlayerDataLoad = 30004,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ACK_PLAYER_DATA_LOAD")] AckPlayerDataLoad = 30005,
    /// <summary>
    /// 请求保存玩家数据
    /// </summary>
    [pbr::OriginalName("REQ_PLAYER_DATA_SAVE")] ReqPlayerDataSave = 30006,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("ACK_PLAYER_DATA_SAVE")] AckPlayerDataSave = 30007,
  }

  #endregion

  #region Messages
  public sealed partial class PlayerData : pb::IMessage<PlayerData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerData> _parser = new pb::MessageParser<PlayerData>(() => new PlayerData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SquickStruct.DbReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerData(PlayerData other) : this() {
      object_ = other.object_ != null ? other.object_.Clone() : null;
      property_ = other.property_ != null ? other.property_.Clone() : null;
      record_ = other.record_ != null ? other.record_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerData Clone() {
      return new PlayerData(this);
    }

    /// <summary>Field number for the "object" field.</summary>
    public const int ObjectFieldNumber = 1;
    private global::SquickStruct.Ident object_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SquickStruct.Ident Object {
      get { return object_; }
      set {
        object_ = value;
      }
    }

    /// <summary>Field number for the "property" field.</summary>
    public const int PropertyFieldNumber = 2;
    private global::SquickStruct.ObjectPropertyList property_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SquickStruct.ObjectPropertyList Property {
      get { return property_; }
      set {
        property_ = value;
      }
    }

    /// <summary>Field number for the "record" field.</summary>
    public const int RecordFieldNumber = 3;
    private global::SquickStruct.ObjectRecordList record_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SquickStruct.ObjectRecordList Record {
      get { return record_; }
      set {
        record_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Object, other.Object)) return false;
      if (!object.Equals(Property, other.Property)) return false;
      if (!object.Equals(Record, other.Record)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (object_ != null) hash ^= Object.GetHashCode();
      if (property_ != null) hash ^= Property.GetHashCode();
      if (record_ != null) hash ^= Record.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (object_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Object);
      }
      if (property_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Property);
      }
      if (record_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Record);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (object_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Object);
      }
      if (property_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Property);
      }
      if (record_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Record);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (object_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Object);
      }
      if (property_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Property);
      }
      if (record_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Record);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerData other) {
      if (other == null) {
        return;
      }
      if (other.object_ != null) {
        if (object_ == null) {
          Object = new global::SquickStruct.Ident();
        }
        Object.MergeFrom(other.Object);
      }
      if (other.property_ != null) {
        if (property_ == null) {
          Property = new global::SquickStruct.ObjectPropertyList();
        }
        Property.MergeFrom(other.Property);
      }
      if (other.record_ != null) {
        if (record_ == null) {
          Record = new global::SquickStruct.ObjectRecordList();
        }
        Record.MergeFrom(other.Record);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (object_ == null) {
              Object = new global::SquickStruct.Ident();
            }
            input.ReadMessage(Object);
            break;
          }
          case 18: {
            if (property_ == null) {
              Property = new global::SquickStruct.ObjectPropertyList();
            }
            input.ReadMessage(Property);
            break;
          }
          case 26: {
            if (record_ == null) {
              Record = new global::SquickStruct.ObjectRecordList();
            }
            input.ReadMessage(Record);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (object_ == null) {
              Object = new global::SquickStruct.Ident();
            }
            input.ReadMessage(Object);
            break;
          }
          case 18: {
            if (property_ == null) {
              Property = new global::SquickStruct.ObjectPropertyList();
            }
            input.ReadMessage(Property);
            break;
          }
          case 26: {
            if (record_ == null) {
              Record = new global::SquickStruct.ObjectRecordList();
            }
            input.ReadMessage(Record);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
