// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game_manager.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SquickStruct {

  /// <summary>Holder for reflection information generated from game_manager.proto</summary>
  public static partial class GameManagerReflection {

    #region Descriptor
    /// <summary>File descriptor for game_manager.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameManagerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJnYW1lX21hbmFnZXIucHJvdG8SDFNxdWlja1N0cnVjdBoKYmFzZS5wcm90",
            "byorCg5HYW1lTWFuYWdlclJQQxIZChVHQU1FX01BTkFHRVJfUlBDX05PTkUQ",
            "AGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SquickStruct.BaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SquickStruct.GameManagerRPC), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 35000 ~ 40000
  /// </summary>
  public enum GameManagerRPC {
    [pbr::OriginalName("GAME_MANAGER_RPC_NONE")] None = 0,
  }

  #endregion

}

#endregion Designer generated code
